# Generated by Django 4.1.4 on 2022-12-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=48)),
                ('brand', models.CharField(max_length=48)),
                ('number', models.CharField(max_length=6, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
