# Generated by Django 4.1.4 on 2022-12-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='adress',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
